### ISSUE TITLE
Failure to build on Windows for arm-linux-androideabi

### ISSUE THREAD

**Issue by david-allison-1** [alexcrichton/openssl-src-rs#64]
Note: Could also be an issue with `openssl-sys 0.9.58`

[relevant-log.txt](https://github.com/alexcrichton/openssl-src-rs/files/4794238/relevant-log.txt)

The line: `self.run_command(build, "building OpenSSL");` fails with:

 `/bin/sh: E:AndroidSDKndk21.1.6352462toolchainsllvmprebuiltwindows-x86_64binarmv7a-linux-androideabi28-clang.cmd: command not found` 
when compiling for `arm-linux-androideabi` on Windows 7.

I believe this is due to an issue with escaping of the `CC` variable in the Makefile

[build.txt](https://github.com/sfackler/rust-openssl/files/4794126/build.txt) - (bat) script used
[Makefile.txt](https://github.com/alexcrichton/openssl-src-rs/files/4794243/Makefile.txt)
[configdata.dump.txt](https://github.com/alexcrichton/openssl-src-rs/files/4794247/configdata.dump.txt) - `perl configdata.pm --dump`

I'm new to Rust, please let me know if I can provide more information.

toml (with trivial `rs` file)

```toml
[package]
name = "rsdroid"
version = "0.1.0"

[lib]
crate_type = ["dylib"]

[dependencies]

[target.'cfg(linux)'.dependencies]
reqwest = { version = "0.10.1", features = ["json", "socks", "native-tls-vendored"] }

[target.'cfg(not(linux))'.dependencies]
reqwest = { version = "0.10.1", features = ["json", "socks"] }
```
